# bd = Baudrate

Pyrometer_KW:
  Kurzwellig 1:
    com:      '/dev/ttyUSB2'    
    bd:       115200              
    parity:   'E'
    stopbits: 1
    bytesize: 8
    emis:     100
    trans:    100
    t90:      '7'

Pyrometer_LW:
  Schnittstelle:
    com:      '/dev/ttyACM0'    
    bd:       19200              
    parity:   'E'
    stopbits: 1
    bytesize: 8
  Geraete:
    Langwellig AV 20:1:
      emis:     100
      array_num:  1      
    Langwellig AV 10:1:  
      emis:     100
      array_num:  2

Pt100:
  Pt Oberfläche:
    GPIO:   D16
    res:    100
    refres: 430 
    wire:   4
    Vergleichssensor: True
  Pt Seite Links:
    GPIO:   D24
    res:    100
    refres: 430 
    wire:   4
    Vergleichssensor: False
  Pt im Körper:
    GPIO:   D23
    res:    100
    refres: 430 
    wire:   4
    Vergleichssensor: False

Heizer:
  Schnittstelle:
    com:      '/dev/ttyUSB0'    
    bd:       9600              
    parity:   'E'
    stopbits: 1
    bytesize: 7
  Auswahl:
    String: Eurotherm       # IKA = IKA Heizplatte, Eurotherm = Eurotherm

Eurotherm:
  gid:  0
  uid:  3
  kp:   
  ti:   
  td:   

Strings:
  Regelsensor:  'Thermoelement K'
  Rezept:       Messreihe_Rezept.txt
  
Delay:
  Heizer:  0.3 # in s